-- CHANNEL

create table if not exists public.sys_channel (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text not null,
  is_active boolean null default true,
  channel_no text not null,
  country text not null,
  currency text not null,
  timezone text not null,
  constraint sys_channel_pkey primary key (id),
  constraint sys_channel_channel_no_key unique (channel_no)
) TABLESPACE pg_default;

-- FUNCTION on_sys_channel_insert
drop function if exists public.on_sys_channel_insert cascade;

create function public.on_sys_channel_insert () returns trigger
set
  search_path = '' as $$ -- PRIVATE FUNCTION
declare
begin
  new.country := UPPER(new.country); -- COUNTRY IS IN UPPERCASE

return new;
end;
$$ language plpgsql security definer;

create trigger on_sys_channel_insert before insert on sys_channel for each row
execute function on_sys_channel_insert ();
