-- PROVIDER

create table public.sys_provider (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  provider_no text not null,
  full_provider_no text null,
  name text not null,
  is_active boolean null default true,
  service_no text not null,
  auth_id uuid null,
  score double precision null default '0'::double precision,
  ai_role text null,
  ai_name text null,
  ai_rules text null,
  country text null,
  cs_phone text null,
  currency text null,
  timezone text null,
  is_voice boolean null default false,
  minimax_group_id text null,
  minimax_language_boost text null,
  minimax_voice_setting_vol double precision null default '1'::double precision,
  minimax_voice_setting_pitch double precision null default '0'::double precision,
  minimax_voice_setting_speed double precision null default '1'::double precision,
  minimax_voice_setting_voice_id text null,
  constraint sys_provider_pkey primary key (id),
  constraint sys_provider_full_provider_no_key unique (full_provider_no),
  constraint sys_provider_auth_id_fkey foreign KEY (auth_id) references auth.users (id),
  constraint sys_provider_service_no_fkey foreign KEY (service_no) references sys_service (full_service_no) on update CASCADE
) TABLESPACE pg_default;

-- FUNCTION on_sys_provider_insert
drop function if exists public.on_sys_provider_insert cascade;

create function public.on_sys_provider_insert () returns trigger
set
  search_path = '' as $$ -- PRIVATE FUNCTION
declare
  _sys_service public.sys_service;
begin
  -- find service
  SELECT * FROM public.sys_service WHERE full_service_no = new.service_no INTO _sys_service;

  -- override
  new.country = _sys_service.country;
  new.currency = _sys_service.currency;
  new.timezone = _sys_service.timezone;

  new.full_provider_no := new.service_no || ':' || new.provider_no;

return new;
end;
$$ language plpgsql security definer;

create trigger on_sys_provider_insert before insert on sys_provider for each row
execute function on_sys_provider_insert ();
