-- MEMBER DATA

create table if not exists public.sys_member_data (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  auth_id uuid null,
  credits double precision null default '0'::double precision,
  tokens double precision null default '0'::double precision,
  constraint sys_member_data_pkey primary key (id),
  constraint sys_member_data_auth_id_key unique (auth_id),
  constraint sys_member_data_auth_id_fkey foreign KEY (auth_id) references auth.users (id)
) TABLESPACE pg_default;