-- CHAT MEMORY

create table public.n8n_chat_memory (
  id bigint generated by default as identity not null,
  session_id character varying(255) not null,
  message jsonb not null,
  created_at timestamp with time zone null default now(),
  constraint n8n_chat_memory_pkey primary key (id)
) TABLESPACE pg_default;

-- FUNCTION n8n_chat_memory_cleanup
drop function if exists public.n8n_chat_memory_cleanup cascade;

create function public.n8n_chat_memory_cleanup () returns void
set
  search_path = '' as $$ -- private
declare
begin
  -- delete all n8n_chat_memory created 60 minutes ago
  delete from public.n8n_chat_memory where
    created_at < now() - interval '60 minutes';
end;
$$ language plpgsql security definer
set statement_timeout to '5min'; -- timeout in 5 minutes

-- CRON
SELECT cron.unschedule((select jobid from cron.job where command = 'SELECT n8n_chat_memory_cleanup();'));
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'n8n_chat_memory_cleanup_30m') THEN
    PERFORM cron.unschedule('n8n_chat_memory_cleanup_30m');
  END IF;
END $$;
SELECT cron.schedule(
  'n8n_chat_memory_cleanup_30m',
  '*/30 * * * *',
  'SELECT n8n_chat_memory_cleanup();'
);

select * from cron.job;
