-- USER MEMORY

create table public.n8n_user_memory (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone null default now(),
  memory text null,
  score bigint null default '0'::bigint,
  user_id text null,
  media text null,
  channel text null,
  constraint n8n_user_memory_pkey primary key (id),
  constraint n8n_user_memory_user_id_channel_memory unique (user_id, channel, memory)
) TABLESPACE pg_default;

-- CONSTRAINT
alter table public.n8n_user_memory drop constraint if exists n8n_user_memory_user_id_channel_memory cascade;
alter table public.n8n_user_memory add constraint n8n_user_memory_user_id_channel_memory unique (user_id, channel, memory);
