-- MSG CHAT

create table public.msg_chat (
  id bigint generated by default as identity not null,
  session_id character varying(255) null,
  message text null,
  user_id text null,
  name text null,
  created_at timestamp with time zone null default now(),
  media text null,
  user_type text null,
  auth_id uuid null,
  message_id text null,
  reply_id text null,
  channel_no text null,
  provider_no text null,
  constraint msg_chat_pkey primary key (id),
  constraint msg_chat_channel_no_fkey foreign KEY (channel_no) references sys_channel (channel_no) on update CASCADE on delete set null,
  constraint msg_chat_provider_no_fkey foreign KEY (provider_no) references sys_provider (full_provider_no) on update CASCADE
) TABLESPACE pg_default;

-- FUNCTION msg_chat_cleanup
drop function if exists public.msg_chat_cleanup cascade;

create function public.msg_chat_cleanup () returns void
set
  search_path = '' as $$ -- private
declare
begin
  -- delete all msg_chat created 24 hours ago
  delete from public.msg_chat where
    created_at < now() - interval '24 hours';
end;
$$ language plpgsql security definer
set statement_timeout to '5min'; -- timeout in 5 minutes

-- CRON
SELECT cron.unschedule((select jobid from cron.job where command = 'SELECT msg_chat_cleanup();'));
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'msg_chat_cleanup_60m') THEN
    PERFORM cron.unschedule('msg_chat_cleanup_60m');
  END IF;
END $$;
SELECT cron.schedule(
  'msg_chat_cleanup_60m',
  '*/60 * * * *',
  'SELECT msg_chat_cleanup();'
);

select * from cron.job;
